# Generated by Django 4.2 on 2023-07-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarks',
            name='popularity',
        ),
        migrations.AddField(
            model_name='remarks',
            name='disappoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remarks',
            name='funny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remarks',
            name='heart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remarks',
            name='insightful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remarks',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
