# Generated by Django 4.2 on 2023-06-08 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import message.models.conversation_model


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_online'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0002_botmessages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botmessages',
            old_name='conversation',
            new_name='discussion',
        ),
        migrations.CreateModel(
            name='GroupConversation',
            fields=[
                ('uuid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.uuid')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='group_conversation/default-conversation.png', upload_to=message.models.conversation_model.conversation_photo_path)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.uuid',),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('uuid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.uuid')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.uuid',),
        ),
        migrations.AddField(
            model_name='messages',
            name='conversation_on',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='message.conversation'),
            preserve_default=False,
        ),
    ]
