# Generated by Django 4.2 on 2023-04-28 19:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import profiles.models.profile_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.uuid')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=25)),
                ('profile_image', models.ImageField(upload_to=profiles.models.profile_model.profile_photo_path)),
                ('cover_image', models.ImageField(default='cover/default-cover.png', upload_to=profiles.models.profile_model.cover_photo_path)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('about', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=5)),
                ('education', models.CharField(blank=True, choices=[('metric', 'Metric'), ('intermediate', 'Intermediate'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'Phd')], max_length=24)),
                ('current_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('unmarried', 'Unmarried'), ('divorce', 'Divorce'), ('widow', 'Widow'), ('widower', 'Widower')], max_length=18)),
                ('employment_status', models.CharField(blank=True, choices=[('student', 'Student'), ('worker', 'worker'), ('employee', 'Employee'), ('self-employed', 'Self-Employed')], max_length=26)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('location', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.uuid',),
        ),
    ]
