# Generated by Django 3.2.5 on 2022-11-17 13:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('unmarried', 'Unmarried'), ('divorce', 'Divorce'), ('widow', 'Widow'), ('widower', 'Widower')], max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('metric', 'Metric'), ('intermediate', 'Intermediate'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'Phd')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('worker', 'worker'), ('employee', 'Employee'), ('self-employed', 'Self-Employed')], max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=5),
        ),
    ]
