# Generated by Django 3.2.5 on 2023-01-24 19:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('unmarried', 'Unmarried'), ('divorce', 'Divorce'), ('widow', 'Widow'), ('widower', 'Widower')], max_length=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, choices=[('metric', 'Metric'), ('intermediate', 'Intermediate'), ('bachelors', 'Bachelors'), ('masters', 'Masters'), ('phd', 'Phd')], max_length=24),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('worker', 'worker'), ('employee', 'Employee'), ('self-employed', 'Self-Employed')], max_length=26),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
