# Generated by Django 4.2 on 2023-10-04 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_signuptoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuptoken',
            name='expired_at',
        ),
        migrations.AddField(
            model_name='signuptoken',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 13, 14, 16, 353155, tzinfo=datetime.timezone.utc)),
        ),
    ]
