# Generated by Django 3.2.5 on 2022-09-25 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models.post_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.uuid')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('other_files', models.FileField(upload_to=post.models.post_model.post_uploaded_files)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.uuid',),
        ),
    ]
