# Generated by Django 4.2.5 on 2023-02-15 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import supermarket.models.products_model
import supermarket.models.stores_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('uuid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.uuid')),
                ('type', models.CharField(max_length=150, unique=True)),
                ('valid_name', models.BooleanField(default=False)),
            ],
            bases=('core.uuid',),
        ),
        migrations.CreateModel(
            name='StoreTypes',
            fields=[
                ('uuid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.uuid')),
                ('type', models.CharField(max_length=150, unique=True)),
                ('valid_name', models.BooleanField(default=False)),
            ],
            bases=('core.uuid',),
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('uuid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.uuid')),
                ('store_name', models.CharField(max_length=155, unique=True)),
                ('images', models.FileField(default='default.png', upload_to=supermarket.models.stores_model.store_files_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('location', models.JSONField(blank=True, null=True)),
                ('store_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.storetypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.uuid',),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('uuid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.uuid')),
                ('product_name', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('images', models.FileField(default='default.png', upload_to=supermarket.models.products_model.product_media_path)),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.producttypes')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.stores')),
            ],
            bases=('core.uuid',),
        ),
    ]
