# Generated by Django 4.2 on 2023-08-27 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usersensitiveinformation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('uuid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.uuid')),
                ('country_code', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('street_address', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('meta', models.JSONField(default=dict)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.uuid',),
        ),
    ]
